### ISSUE TITLE
dyeable chickens doesn't like being dyed with non-vanilla dyes

### ISSUE THREAD

**Issue by bafomdad** [Hoborific/DyeableChickens#1]
what I expected to happen: being able to dye dyeable chickens with non-vanilla dyes

the issue causing this: when dyeing chickens, it compares for instances of ItemDye, which mods seem to rarely extend, and instead, uses OreDictionary entries.

the resolution that can be attempted: letting dyeable chickens take in oredictionary stuff concerning dyes

**Comment by Hoborific** [comment]
Presumably fixed.
