### ISSUE TITLE
Dyeable chickens are spawning underground/by hostile mob rules

### ISSUE THREAD

**Issue by janskydunbird** [Hoborific/DyeableChickens#2]
On 1.11.2 - didn't see any chickens in the world at first but individuals have started showing up over time on the surface and underground. Looks like they're spawning under hostile mob rules, which will eventually cause problems with quantities of chickens spawning in caves, zombies picking up the eggs and filling hostile mob cap. As with early chicken jockey issues in vanilla.

**Comment by Hoborific** [comment]
What mods and forge version are you using? To briefly describe the current spawn process, when vanilla spawns the chicken naturally, I replace it with my own version, this happens no matter how the chicken spawns and currently it breaks chicken jockeys as the jockey is dismounted when the chicken is replaced, which describes the strange apparent spawn behavior of chickens underground at the moment.

**Comment by janskydunbird** [comment]
Forge ver was 1.11.2-13.20.1.2386. I had a few other mods but nothing that would have changed spawns (mostly things like HarvestCraft and RealTimeClock). Now that I think about it, it's probably chicken jockeys as you say. Unfortunately it's forced me to remove the mod as I was seeing more and more chickens underground in loaded chunks with a corresponding increase in egg-holding zombies :( 

EDIT: A thought. Instead of straight-up replacing vanilla chickens, any chance of making it so that your version doesn't spawn naturally but use of a dye on the chicken converts it to a dyeable chickens one? I'm no coder so I don't know if it's even possible, but if it is one could preserve the vanilla chicken jockey behavior.

**Comment by Hoborific** [comment]
As it currently stands, there is only a 0.0275% chance of a baby zombie being spawned as a chicken jockey that would create a dyeable chicken underground, There is no way to my knowledge that they are spawning underground under normal conditions, especially as "hostile mob rules" as you imply, I am going to close this issue. Please feel free to reopen if you have further to add or more information relating to the issue.
